### ISSUE TITLE
when Ubuntu 22 reboot, FileNotFoundError '/tmp/gef/skip-venv'

### ISSUE THREAD

**Issue by WarmW1Nd** [bata24/gef#58]
this is the error

Loading GEF...
Traceback (most recent call last):
  File "/home/jhon/bata24-gef/gef.py", line 80579, in <module>
    main()
  File "/home/jhon/bata24-gef/gef.py", line 80499, in main
    fix_venv()
  File "/home/jhon/bata24-gef/gef.py", line 80487, in fix_venv
    open(skip_config, "w").close()
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/gef/skip-venv'

because Ubuntu reboot delete /tmp/gef, but gef not auto create

**Comment by WarmW1Nd** [comment]
fix_venv()

if not os.path.exists(GEF_TEMP_DIR):
   os.mkdir(GEF_TEMzP_DIR)


create tmp dir should first by fix_venv()

**Comment by bata24** [comment]
Sorry, it was fixed.
